### ISSUE TITLE
Dev environment?

### ISSUE THREAD

**Issue by benvogler** [team-monumental/monuments-and-memorials#20]
We should figure out if we actually want a dev environment, specifically what benefits it poses, and make a user story for it if we do. Considering the limited resources of the VM I think it would have to be on a different host which doesn't feel worth the effort.

If we opt out of having a hosted dev environment I think we should get rid of the dev branch and just use GitHub's tags/releases to signify what commit is currently deployed to prod. I did a test of that here https://github.com/team-monumental/monuments-and-memorials/releases/tag/0.1.0

**Comment by njd9419** [comment]
Fully agree that having a dev environment and branch is not worth the effort.

**Comment by benvogler** [comment]
Deleted dev for the time being
