### ISSUE TITLE
Add 404 errors to the API

### ISSUE THREAD

**Issue by benvogler** [team-monumental/monuments-and-memorials#9]
Currently if you do a GET to `/api/monument/<id that doesn't exist>` you just get an empty JSON response. This should be responding with a 404 error instead

```java
import me.alidg.errors.annotation.ExceptionMapping;
import org.springframework.http.HttpStatus;

@ExceptionMapping(statusCode = HttpStatus.NOT_FOUND, errorCode = "notFound")
public class NotFoundException extends RuntimeException
```

**Comment by njd9419** [comment]
Turning this into a User Story and adding it to the Sprint Backlog. Do you want to take this or want me to? I don't mind taking it, don't have much to do. Up to you.
